### ISSUE TITLE
Astro does not work on latest master

### ISSUE THREAD

**Issue by nahtnam** [AndreaPontrandolfo/sheriff#213]
I was working on a PR so I tried the CLI with the latest master locally. Astro does not seem to work

```
npx eslint .

Oops! Something went wrong! :(

ESLint: 9.9.0

TypeError: context.getScope is not a function
Occurred while linting /my-app/astro.config.mjs:1
Rule: "sonarjs/no-gratuitous-expressions"
    at Identifier (/my-app/node_modules/.pnpm/eslint-plugin-sonarjs@0.19.0_eslint@9.9.0/node_modules/eslint-plugin-sonarjs/lib/rules/no-gratuitous-expressions.js:81:54)
    at ruleErrorHandler (/my-app/node_modules/.pnpm/eslint@9.9.0/node_modules/eslint/lib/linter/linter.js:1124:48)
    at /my-app/node_modules/.pnpm/eslint@9.9.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/my-app/node_modules/.pnpm/eslint@9.9.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/my-app/node_modules/.pnpm/eslint@9.9.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/my-app/node_modules/.pnpm/eslint@9.9.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/my-app/node_modules/.pnpm/eslint@9.9.0/node_modules/eslint/lib/linter/node-event-generator.js:337:14)
    at runRules (/my-app/node_modules/.pnpm/eslint@9.9.0/node_modules/eslint/lib/linter/linter.js:1168:40)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/my-app/node_modules/.pnpm/eslint@9.9.0/node_modules/eslint/lib/linter/linter.js:1947:31)
```

It's an empty astro application. I selected no for ts-patch because eslint comes with experimental ts support now

**Comment by AndreaPontrandolfo** [comment]
The problem seems to be `eslint-plugin-sonarjs`, not astro.
But the version of `eslint-plugin-sonarjs` that i see in the stacktrace seems to be outdated, it's not the current one.
The version of `eslint-plugin-sonarjs` that Sheriff is currently employing on `master` is `1.0.4`.
Can you verify that this is not a false-positive? Or maybe provide a simple reproduction repo?

**Comment by AndreaPontrandolfo** [comment]
Im closing this issue for inactivity and a reproduction repo was not provided.

The current Astro integration support is not perfect, but we already have https://github.com/AndreaPontrandolfo/sheriff/issues/316 tracking it.
