### ISSUE TITLE
crash on setup in new monorepo

### ISSUE THREAD

**Issue by cyrfer** [AndreaPontrandolfo/sheriff#48]
Hi,
I'm excited to try Sheriff. I just created a new monorepo, and added one package. Then I ran the [automatic setup](https://sheriffrc.gitbook.io/sheriff/sheriff/setup/automatic-setup) from [within the package folder](https://sheriffrc.gitbook.io/sheriff/sheriff/monorepo-support), but I saw a crash:

```
cd packages/parse-pdf
npx create-sheriff-config 
Need to install the following packages:
create-sheriff-config@2.9.1
Ok to proceed? (y) 
verbose: ▪ 'eslint.config.js' file not found. Generating and configuring 'eslint.config.js' file...
warn:    ▪ ⚠️  If you have other Eslint configs in your project, remove them.
verbose: ┏ Setting Sheriff with options:
verbose: ┃ [1] {
verbose: ┃ [2]   react: false,
verbose: ┃ [3]   lodash: false,
verbose: ┃ [4]   next: false,
verbose: ┃ [5]   playwright: false,
verbose: ┃ [6]   jest: false,
verbose: ┃ [7]   vitest: false
verbose: ┗ [8] }
info:    ▪ ✔️  Successfully generated eslint.config.js file.
verbose: ▪ No 'prettier' configuration was found in the project. Generating and configuring '.prettierrc.json' file...
info:    ▪ ✔️  Successfully generated .prettierrc.json file.
verbose: ▪ No '.prettierignore' file was found in the project. Generating and configuring '.prettierignore' file...
verbose: ▪ Installing 'eslint'...
verbose: ▪ Installing 'eslint-define-config'...
verbose: ▪ Installing 'eslint-config-sheriff'...
error:   ▪ ❌  Couldn't walk up the filesystem. Error: Command failed with ENOENT: pnpm --version
spawn pnpm ENOENT
file:///Users/john/.npm/_npx/1cf4107118993e1f/node_modules/create-sheriff-config/dist/index.js:84
  throw new Error(`${isString(error) ? error : String(error)}`);
        ^

Error: Error: Command failed with ENOENT: pnpm --version
spawn pnpm ENOENT
    at printError (file:///Users/john/.npm/_npx/1cf4107118993e1f/node_modules/create-sheriff-config/dist/index.js:84:9)
    at autoInstallPackages (file:///Users/john/.npm/_npx/1cf4107118993e1f/node_modules/create-sheriff-config/dist/index.js:125:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async setDependencies (file:///Users/john/.npm/_npx/1cf4107118993e1f/node_modules/create-sheriff-config/dist/index.js:144:3)
    at async main (file:///Users/john/.npm/_npx/1cf4107118993e1f/node_modules/create-sheriff-config/dist/index.js:477:3)

Node.js v18.17.0
```

**Comment by AndreaPontrandolfo** [comment]
Hey @cyrfer , let me know if the proposed solution solved your issue!

**Comment by AndreaPontrandolfo** [comment]
Hey @cyrfer, i actually ended up contributing this detail of documentation in the official website docs!
[Here it is](https://www.eslint-config-sheriff.dev/docs/monorepo-support#setup-with-create-sheriff-config)

I'm closing the issue now.
